<?php
// $Id$
/**
 * @file
 * Implementation of "Ip address" module.
 */

/**
 * Implements hook_menu().
 */
function ip_address_menu() {
  $items['ip'] = array(
    'title' => 'Your IP address is:',
    'page callback' => 'ip_address_view',
    'access arguments' => array('access content'),
    'description' => 'View your IP address.',
  );
  $items['admin/config/system/ip_address'] = array(
    'title' => 'Ip address',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ip_address_settings'),
    'access arguments' => array('administer site configuration'),
    'description' => 'Administer settings for Ip address module.',
  );

  return $items;
}

/**
 * Page callback.
 */
function ip_address_view($format = 'html') {
  // Disable caching unless we're using html format, which uses
  // javascript and therefore can be page cached.
  if ($format != 'html') {
    drupal_page_is_cacheable(FALSE);
  }

  // Output in the correct format.
  switch ($format) {
    case 'txt':
    case 'text':
    case 'plain':
    case 'raw':
      drupal_add_http_header('Content-Type', 'text/plain');
      print ip_address();
      break;
    case 'json':
      drupal_json_output(array('ip_address' => ip_address()));
      break;
    case 'xml':
      // @todo: xml format.
    case 'html':
    default:
      $geoip = '';
      if (variable_get('ip_address_show_geoip', FALSE)) {
        drupal_add_js('http://j.maxmind.com/app/geoip.js', array('type' => 'external', 'scope' => 'footer'));
        drupal_add_js(drupal_get_path('module', 'ip_address') . '/ip_address.js', array('type' => 'file', 'scope' => 'footer'));
        $geoip = '<div id="ip_geoip"></div>';
        $geoip .= '<div class="attribution">' . t('Geo IP service provided by !link', array('!link' => l('www.maxmind.com', 'http://www.maxmind.com/', array('external' => TRUE)))) . '</div>';
      }
      drupal_add_js(array('ip_address_path' => drupal_get_path('module', 'ip_address')), 'setting');
      return '<div id="ip_address">&nbsp;<noscript><p>Oops, this service requires javascript enabled.</p></noscript></div>' . $geoip;
  }
}

function ip_address_settings() {
  $form['ip_address_show_geoip'] = array(
    '#type' => 'checkbox',
    '#title' => t('Show geo IP information'),
    '#description' => t("This feature uses a geo IP service provided by !maxmind to show the user's city and state.", array('!maxmind' => l('MaxMind', 'http://www.maxmind.com/'))),
    '#default_value' => variable_get('ip_address_show_geoip', FALSE),
  );

  return system_settings_form($form);
}

